- src: dilerous.vxflex_mdminstall_all
  name: vxflex_mdminstall_all

- src: ericsysmin.chrony
  name: ericsysmin.chrony

- src: dilerous.vxflex_mdminstall_gateway
  name: vxflex_mdminstall_gateway

- src: dilerous.vxflex_adddrives
  name: vxflex_adddrives

- src: dilerous.vxflex_addsds
  name: vxflex_addsds

- src: dilerous.vxflex_createpdandsp
  name: vxflex_createpdandsp

- src: dilerous.vxflex_createcluster
  name: vxflex_createcluster

- src: dilerous.vxflex_install_sdc
  name: vxflex_install_sdc
