- src: dilerous.vxflex_mdminstall_all
  name: vxflex_mdminstall_all
  version: v1.0.1

- src: ericsysmin.chrony
  name: ericsysmin.chrony

- src: dilerous.vxflex_mdminstall_gateway
  name: vxflex_mdminstall_gateway
  version: v1.0.1

- src: dilerous.vxflex_adddrives
  name: vxflex_adddrives
  version: v1.0.1

- src: dilerous.vxflex_addsds
  name: vxflex_addsds
  version: v1.0.3

- src: dilerous.vxflex_createpdandsp
  name: vxflex_createpdandsp
  version: v1.0.3

- src: dilerous.vxflex_createcluster
  name: vxflex_createcluster
  version: v1.0.3

- src: dilerous.vxflex_install_sdc
  name: vxflex_install_sdc
  version: v1.0.3
